import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./(components)/SessionProvider";
import { UserProvder } from "./(components)/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  // if session is not null then call backend to get the data from user table
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <UserProvder userInfo={{ name: session?.user?.name }}>
            {children}
          </UserProvder>
        </SessionProvider>
      </body>
    </html>
  );
}
